# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gemfile_updater 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gemfile_updater"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jason Hutchens"]
  s.date = "2015-06-27"
  s.description = "Does what it says on the tin."
  s.email = "jasonhutchens@gmail.com"
  s.executables = ["gemfile_updater"]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "UNLICENSE",
    "VERSION",
    "bin/gemfile_updater",
    "gemfile_updater.gemspec",
    "lib/gemfile_updater.rb",
    "lib/gemfile_updater/main.rb"
  ]
  s.homepage = "http://github.com/JasonHutchens/gemfile_updater"
  s.licenses = ["UNLICENSE"]
  s.required_ruby_version = Gem::Requirement.new("~> 2.2")
  s.rubygems_version = "2.4.7"
  s.summary = "Update your Gemfile with pessimistic versions from Gemfile.lock."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<byebug>, ["~> 5.0"])
      s.add_development_dependency(%q<awesome_print>, ["~> 1.6"])
      s.add_development_dependency(%q<github_changelog_generator>, ["~> 1.6"])
    else
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<byebug>, ["~> 5.0"])
      s.add_dependency(%q<awesome_print>, ["~> 1.6"])
      s.add_dependency(%q<github_changelog_generator>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<rdoc>, ["~> 4.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<byebug>, ["~> 5.0"])
    s.add_dependency(%q<awesome_print>, ["~> 1.6"])
    s.add_dependency(%q<github_changelog_generator>, ["~> 1.6"])
  end
end

